### PR TITLE
Replace snappy with cramjam

### PR DESCRIPTION
**Pull request by gliptak**

### CODE REVIEW

**Comment by gliptak** [comment]
@taylorfturner please assign reviewers

**Comment by taylorfturner** [comment]
Thanks for your patience @gliptak

**Comment by gliptak** [comment]
please review

**Comment by gliptak** [comment]
https://github.com/capitalone/synthetic-data/pull/346

**Comment by taylorfturner** [comment]
@gliptak rebase onto `dev` and I'll approve

**Comment by taylorfturner** [comment]
rebase or `update branch` on this and I'll approve @gliptak

**Comment by gliptak** [comment]
green for your review @taylorfturner

**Review by taylorfturner — APPROVED** [review]
LGTM

**Comment by gliptak** [comment]
@micdavis @ksneab7 please review/approve

**Review by micdavis — APPROVED** [review]

**Comment by taylorfturner** [comment]
@gliptak are you able to restore your `cramjam1` branch? 

This change fails tests locally on this command `DATAPROFILER_SEED=0 python3 -m unittest discover -p "test*.py"`

First issues is ```dataprofiler/dataprofiler/tests/test_dp_logging.py", line 27, in test_default_verbosity
    self.assertEqual(
AssertionError: 20 != 30```

Second issue is ```dataprofiler/dataprofiler/tests/test_data_profiler.py", line 32, in test_set_seed
    self.assertEqual(dp.settings._seed, None)
AssertionError: 0 != None```

`main` testing works locally and the only diff between `main` and `dev` is this PR

**Comment by taylorfturner** [comment]
Checking out `f8b3e5dbd4b76f0ecc291911ace9e8e21cf1ecb1` and running tests on that commit (one commit prior to this PR) ensures that tests did run on `dev` locally at that point in the history

**Comment by taylorfturner** [comment]
Glad to ultimately do cramjam + python 3.11 -- these tests will just need to pass locally as well as remote

**Comment by gliptak** [comment]
@taylorfturner restored branch

as the build was green for this PR, might that indicate that different library versions where used?

**Comment by taylorfturner** [comment]
potentially -- I tried a bunch of different scenarios and wasn't able to find a setup where the above two tests passed locally

**Comment by gliptak** [comment]
I did reproduce the fail locally and still cannot reproduce in GHA

the one difference I observed is that local is `Python 3.10.12` while GHA is `CPython (3.10.13)

**Pull request merged**
