### PR TITLE
Updating docs to v0.5.0

### PR DESCRIPTION
**Pull request by gme5078**
https://gme5078.github.io/data-profiler/

Key changes is unstructured is included in areas where it is appropriate.

### CODE REVIEW

**Comment by gme5078** [comment]
This is also supposed to fix this issue: https://github.com/capitalone/DataProfiler/issues/230

**Comment by JGSweets** [comment]
Code blocks in dark theme are difficult to read.

**Review by JGSweets — CHANGES_REQUESTED** [review]
Few changes requested bc theme issues.

**Comment by lettergram** [comment]
@JGSweets how do you even get to dark theme in the docs? I have it setup on github and don't see anything.

**Comment by lettergram** [comment]
LGTM btw

**Comment by JGSweets** [comment]
@lettergram i think it is just the github setting. i don't think i'ved changed it elsewhere.

**Comment by JGSweets** [comment]
@lettergram I assume we want to do this and version release together?

**Comment by JGSweets** [comment]
Do you want an jupyter notebook example first before the version release or can that come shortly after?

**Comment by gme5078** [comment]
I think this should get out there before the jupyter notebook tbh

**Comment by JGSweets** [comment]
> I think this should get out there before the jupyter notebook tbh

I didn't mean before this, I meant as in together in one PR. But understood.

**Review by lettergram — APPROVED** [review]

**Pull request merged**
