### PR TITLE
Massive Docs Overhaul

### PR DESCRIPTION
**Pull request by gme5078**
Basically everything has changed as you can see here: https://gme5078.github.io/data-profiler/

For my friends who use dark theme, does it look appropriate?
Any changes you think need to be made?

### CODE REVIEW

**Comment by JGSweets** [comment]
Maybe note this PR, but we should limit the titles of the examples in the left menu bar to be small and catchy:
i.e.
Adding models to a Labeler Pipeline
Sensitive Data Detection w/ the Labeler

Title on page is fine.

**Comment by JGSweets** [comment]
DataReaders should be first IMO

**Comment by JGSweets** [comment]
Otherwise Looks good.

**Comment by lettergram** [comment]
Screenshot from 2021-04-23 22-57-56

**Comment by lettergram** [comment]
- [ ] `Profiler` section should have some basic examples at the top, even if it's just taking from the other section. Explain the statistics 
- [ ] `Data` needs to have a basic example at the top with a basic explanation, even if it's just taking from another section. Explain what we can load, etc
- [ ]  `Labeler`has examples, but should list the label types
- [ ] Should be consistent in the naming `Labeler`, `Profiler`, `Data Reader` (as opposed to `labeling`)
- [ ] Agree with Jeremy: `Data` should be at the top, examples should be concise titles, etc
- [ ] Install section should say: `pip install dataprofiler --user` at the top
- [ ] `Data Profiler Installation` section should say `Build From Scratch` or something

**Review by lettergram — APPROVED** [review]

**Review by JGSweets — APPROVED** [review]

**Pull request merged**
