### PR TITLE
Depedency: `matplotlib` version bump 

### PR DESCRIPTION
**Pull request by taylorfturner**

### CODE REVIEW

**Review by rxm7706 — COMMENTED** [review]
matplotlib>=3.3.3,<3.9.0 might be better - to accommodate patches. 
3.8.2 was released last friday.

**Review by rxm7706 — COMMENTED** [review]
@taylorfturner That still wouldn't pick up 3.8.2 -- did you mean to do <=3.8.2 or <3.9.0

**Comment by rxm7706** [comment]
hi @taylorfturner, 
Did you get a chance to consider using <3.9.0, the current pin will not pick up 3.8.2 or any patch releases in the 3.8 series. 
Thank You.

**Comment by taylorfturner** [comment]
> hi @taylorfturner, Did you get a chance to consider using <3.9.0, the current pin will not pick up 3.8.2 or any patch releases in the 3.8 series. Thank You.

Hey @rxm7706 -- haven't take a look in-depth at this yet. At AWS re:Invent this week as well so the team's response will probably be delayed.

**Review by micdavis — APPROVED** [review]

**Comment by taylorfturner** [comment]
Updated to 3.9.0 @rxm7706

**Review by ksneab7 — APPROVED** [review]

**Comment by taylorfturner** [comment]
@rxm7706 merged FYI -- thanks

**Pull request merged**
