### PR TITLE
Refactor `_assimilate_histogram` and `_regenerate_histogram`

### PR DESCRIPTION
**Pull request by junholee6a**
Issue: https://github.com/capitalone/DataProfiler/issues/820

The functions `_assimilate_histogram` and `_regenerate_histogram` are refactored as directed in the issue. Additionally, `_assimilate_histogram` no longer rounds bin edges, as this feature doesn't seem necessary and adds an additional argument to `_assimilate_histogram`.

### CODE REVIEW

**Comment by junholee6a** [comment]
I didn't add unit tests for these functions here because 1) the functions had no direct unit tests in the first place so code coverage won't change, and 2) `_assimilate_histogram` will be re-written in issue https://github.com/capitalone/DataProfiler/issues/1017

**Comment by junholee6a** [comment]
Seems like there was a mypy error in the Python 3.8 tests. Will look into that

**Comment by taylorfturner** [comment]
> Seems like there was a mypy error in the Python 3.8 tests. Will look into that

thanks!

**Comment by taylorfturner** [comment]
Had to rebuild some branches post `0.10.5` release. Please re-open and change base to `dev` (i.e. the branch you are merging into) @junholee6a

**Comment by taylorfturner** [comment]
reopening

**Pull request closed without merging**
