### PR TITLE
Add Profiler python notebook example

### PR DESCRIPTION
**Pull request by lettergram**

### CODE REVIEW

**Review by gme5078 — DISMISSED** [review]

**Review by AnhTruong — COMMENTED** [review]
this example has a lot of overlap content with another one (intro_data_profiler). Do we plan to merge them or just keep either one of them?

**Review by AnhTruong — COMMENTED** [review]
please remove all outputs

**Review by AnhTruong — CHANGES_REQUESTED** [review]
some errors

```
AttributeError                            Traceback (most recent call last)
<ipython-input-9-17303dd2aeb1> in <module>
      6 
      7 # Save a profile to disk for later use
----> 8 profile.save(filepath="my_profile.pkl")
      9 
     10 # Load a profile from disk

AttributeError: 'Profiler' object has no attribute 'save'
```

**Comment by lettergram** [comment]
@AnhTruong you're using a version of the dataprofiler not in master. Try uninstalling and re-executing the notebook.

**Review by AnhTruong — APPROVED** [review]

**Review by AnhTruong — APPROVED** [review]

**Pull request merged**
