### PR TITLE
docs: fix indentation for structured_options.int.min

### PR DESCRIPTION
**Pull request by carlsonp**
Hopefully this is the right branch?

### CODE REVIEW

**Review by taylorfturner — CHANGES_REQUESTED** [review]
The rendering is looking a little off on my end .... Are you seeing this as well? https://github.com/capitalone/DataProfiler/blob/5a8da4264ed2a1cefc9424e2cc98aed49dd62033/docs/source/profiler.rst#:~:text=int%20%2D%20Options%20for%20the%20integer%20columns

**Comment by taylorfturner** [comment]
I do agree indentation needs a fix though -- good call @carlsonp 

https://capitalone.github.io/DataProfiler/docs/0.10.9/html/profiler.html#:~:text=int%20%2D%20Options%20for%20the%20integer%20columns

**Comment by taylorfturner** [comment]
> Hopefully this is the right branch?

yes indeed!

**Comment by carlsonp** [comment]
There we go, I think it just needed some more spacing.  https://github.com/capitalone/DataProfiler/blob/66eeb758dd8324097024dfc53fa0d2930b4901cb/docs/source/profiler.rst#:~:text=int%20-%20Options%20for%20the%20integer%20columns

**Review by taylorfturner — APPROVED** [review]
LGTM

**Pull request merged**
