### PR TITLE
Updated requirements.py

### PR DESCRIPTION
**Pull request by poyap**
Removed strict version for requests library.

### CODE REVIEW

**Comment by taylorfturner** [comment]
Good morning, @poyap! Is this solving a bug or particular issue on your end when you run the code in the DataProfiler? I'd lean toward making a wider bounds on the `requests` library, but opening up the `requests` version pin to anything is wide open.

**Comment by taylorfturner** [comment]
> Good morning, It was an issue I forgot to mention it, sorry.

Got it -- what exactly is the issue?

**Comment by poyap** [comment]
#716

**Comment by taylorfturner** [comment]
Got it -- you'll definitely need to sign the CLA and then there appears to be an issue on one of the checks for `python3.9`

**Comment by JGSweets** [comment]
@poyap I'm not completely against it, but is this an issue you are experiencing directly? We did have https://github.com/capitalone/DataProfiler/pull/750 which should have relaxed the hard req, but failed to update the issue / close it.

**Comment by taylorfturner** [comment]
> @poyap I'm not completely against it, but is this an issue you are experiencing directly? We did have #750 which should have relaxed the hard req, but failed to update the issue / close it.

+1

**Comment by taylorfturner** [comment]
@poyap good morning, bump on this to make sure it doesn't go stale. Thanks!

**Comment by taylorfturner** [comment]
@poyap bump on this. Thank you!

**Comment by taylorfturner** [comment]
@poyap  just checking in on this PR. Thx

**Comment by taylorfturner** [comment]
Closing, but if you have any thoughts to improve the library or questions feel free to reach back out!

**Pull request closed without merging**
