### PR TITLE
Delay transforming priority_order into ndarray

### PR DESCRIPTION
**Pull request by junholee6a**
Issue: https://github.com/capitalone/DataProfiler/issues/722

In the changed code, we had a mypy error because numpy `ndarray`s are not compatible with `random.Random.shuffle()` (expected argument type is `MutableSequence[Any]`)

We fix this by first instantiating `priority_order` as a list, then shuffling it, then creating an ndarray from it afterwards.

### CODE REVIEW

**Comment by junholee6a** [comment]
> update branch

Will update this branch after PR https://github.com/capitalone/DataProfiler/pull/968 is no longer open

**Review by tyfarnan — DISMISSED** [review]

**Review by ksneab7 — DISMISSED** [review]

**Review by taylorfturner — CHANGES_REQUESTED** [review]
blocking for 0.10.3 release. will unblock post-deployment

**Comment by taylorfturner** [comment]
@junholee6a update and resolve conflict on `requirements.txt` for this PR

**Comment by junholee6a** [comment]
Conflict was fixed and up to date

**Pull request closed without merging**
